### ISSUE TITLE
update_route_tables and route_tables_ids error with Unexpected Attribute

### ISSUE THREAD

**Issue by filipeestacio** [RaJiska/terraform-aws-fck-nat#19]
When trying to use fck-nat as a module in terraform, documentation says that update_route_table and route_table_id is deprecated. However, the recommended variables update_route_tables and route_tables_ids errors out as Unexpected Attribute.

```
module "fck-nat" {
  source = "RaJiska/fck-nat/aws"
  name = "fck-nat-${var.availability_zones[count.index]}"
  vpc_id = aws_vpc.main.id
  subnet_id = aws_subnet.public[count.index].id
  use_spot_instances = true
  instance_type = "t4g.nano"
  update_route_tables = true
  route_tables_ids = {
    "private" = aws_route_table.private[count.index].id
  }
}
```

**Comment by RaJiska** [comment]
It looks like you are pulling from Terraform registry, which latest version is 1.2.0. Many commits have been pushed since but not yet released as part of a new version as I am waiting for NAT64 to be released on the upstream project. You should use the documentation available [here](https://registry.terraform.io/modules/RaJiska/fck-nat/aws/latest) if you intent to use the latest official version.
